const objArray = [
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "08:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "08:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "08:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "14:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "14:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "14:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "10:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "10:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "10:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "16:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "16:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "16:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "09:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "09:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "09:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "14:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "14:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "14:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "11:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "11:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "11:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "08:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "08:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "08:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "13:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "13:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "13:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "16:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "16:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "16:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "12:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "12:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "12:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "17:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "17:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "17:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "11:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "11:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "11:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "18:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "18:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "18:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "09:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "09:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "09:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "15:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "15:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "15:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "12:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "12:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "12:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "17:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "17:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "17:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "10:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "10:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "10:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "13:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "13:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "13:00:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Hot Shave",
        category: "barber",
        price: 50,
        duration: "00:30:00",
        slot_time: "15:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "dye",
        category: "barber",
        price: 75,
        duration: "01:00:00",
        slot_time: "15:30:00",
    },
    {
        id: 20,
        name: "The Baber Shop",
        address: "Charlottenstraße 35",
        geojson: { type: "Point", coordinates: [Array] },
        service_name: "Haircut",
        category: "barber",
        price: 25,
        duration: "00:30:00",
        slot_time: "15:30:00",
    },
];
const slots = () => {
    let newArray = [];
    const isDuplicate = (obj, arr) => {
        return arr.some((x) => obj.id == x.id && obj.slot_time == x.slot_time);
    };

    for (const obj of objArray) {
        if (!isDuplicate(obj, newArray)) {
            console.log("pushing it ");
            newArray.push(obj);
        }
    }
    return newArray;
};

console.log(slots());
console.log(objArray.length);
